### ISSUE TITLE
Redirects are not handled if node is hidden

### ISSUE THREAD

**Issue by markuspfeifenberger** [neos/redirecthandler#39]
If a document node is hidden, the redirect handler does not perform the redirect and a 404 is triggered.

From the perspective of the user, the URL of the (hidden) page does no longer exist in the frontend and if a redirect is defined, it should do a redirect to the defined target.

**Comment by Sebobo** [comment]
As we also have an issue in the NeosAdapter package I close this one as the issue is not related to this package.
