### ISSUE TITLE
URLs with bracket can't be imported

### ISSUE THREAD

**Issue by jonnitto** [neos/redirecthandler#43]
A URL can also have brackets `[]`. But it is not possible to import them, as the systems say the URL is not valid. 

```bash
!! Source path "persoenliche-beratung/clinic[bonn]-1/clinic[augsburg]-1/topicsMen[body1]-1" does not have a valid format
```

![image](https://user-images.githubusercontent.com/4510166/73840866-83bff880-4819-11ea-932f-4c1df5dc2d7e.png)

**Comment by Sebobo** [comment]
As said during the call, you can modify the behaviour by changing the regex of `Neos.RedirectHandler.validation.sourceUriPath` in and `Neos.RedirectHandler.Ui.validation.sourceUriPath`.
The first one is the php regex and the second on the one for Javascript in the UI.

Sadly they have slight differences...

**Comment by Sebobo** [comment]
Should be added to the docs. I thought it was in there already.

**Comment by Sebobo** [comment]
Could you solve it?
